config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users, path: "authorize", path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'cmon_let_me_in'
  }

  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  root 'application#index'

  get 'about' => 'application#about'
  get 'solicit' => 'application#solicit'

  resources :artists

  get 'songs/filter' => 'songs#filter'
  resources :songs

  resources :albums

  resources :genres

  resources :moods

  resources :themes

  resources :messages
    get 'messages/new/project' => 'messages#new_project'

  resources :contacts

  resources :pages

  match ':controller(/:action(/:id(.:format)))', :via => [:get, :post]
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
  has_and_belongs_to_many :genres, :join_table => 'genres_songs'
  has_and_belongs_to_many :moods, :join_table => 'moods_songs'
  has_and_belongs_to_many :themes, :join_table => 'songs_themes'

  # NOTE: Add file attachments
  has_attached_file :cover_art, :styles => { :large => "300x300", :medium => "200x200>", :thumb => "100x100>" }
  validates_attachment_content_type :cover_art,
    :content_type => /\Aimage\/.*\Z/,
    :size => { :less_than => 3.megabytes }

  has_attached_file :audio
  validates_attachment_content_type :audio,
    :content_type => /\Aaudio\/.*\Z/,
    :size => { :less_than => 13.megabytes }

  scope :sorted_by_title, lambda { order("songs.title ASC") }
  # scope :sorted_by_title_reverse, lambda { order("songs.title DESC") }
  # scope :sorted_by_release_date, lambda { order("songs.original_release_date ASC") }
  # scope :sorted_by_release_date_reverse, lambda { order("songs.original_release_date DESC") }

  # scope :search, lambda { |query|
  #   where("title LIKE ?", "%#{query}%")
  # }

  # NOTE: Add pagination
  paginates_per 25

  def self.search(q)

    if q
      # @songs = Song.search(params[:q]).sorted_by_title
      # where("title ILIKE ? OR theme ILIKE ? OR genre ILIKE ? OR mood ILIKE ?", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%")
      where("title ILIKE ?", "%#{q}%")
    # else
      # @songs = Song.all
      # all
    end
  end

  # NOTE: Find songs by mood
  def self.search_mood(uid)
    song_search = Song.joins(:moods).where(moods: {id: uid})
  end

  # NOTE: Find songs by theme
  def self.search_theme(uid)
    song_search = Song.joins(:themes).where(themes: {id: uid})
  end

  # NOTE: Find songs by genre
  def self.search_genre(uid)
    song_search = Song.joins(:genres).where(genres: {id: uid})
  end

  # # NOTE: Find songs by album
  # def self.search_album(uid)
  #   song_search = Song.joins(:albums).where(albums: {id: uid})
  # end

  # # NOTE: Find songs by artist
  # def self.search_artist(uid)
  #   song_search = Song.joins(:albums).where(albums: {id: uid})
  # end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy, :create]
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :get_albums, only: [:edit, :new, :update, :create]
  before_action :get_genres, only: [:edit, :new, :update, :create]
  before_action :get_moods, only: [:edit, :new, :update, :create]
  before_action :get_themes, only: [:edit, :new, :update, :create]

  def filter
    # NOTE: Filter on genres
    if params[:genres].present?
      # NOTE: Get all songs with the requested genre(s)
      songs = Song.joins(:genres).where("genre_id IN (?)", params[:genres])

      # NOTE: Get the titles of the selected genres and put them in a sentence
      genres = Genre.make_sentence(params[:genres])

      # NOTE: Make sure we got some songs back
      if songs.present?
        @songs = songs.uniq.sorted_by_title.page params[:page]
        flash[:success] = ' Filtering song genres on ' + genres + '.'
      else
        flash[:alert] = ' There are no songs matching genres: ' + genres + '.'
      end
    end

    # NOTE: Filter on moods
    if params[:moods].present?
      # NOTE: Get all songs with the requested mood(s)
      songs = Song.joins(:moods).where("mood_id IN (?)", params[:moods])

      # NOTE: Get the titles of the selected moods and put them in a sentence
      moods = Mood.make_sentence(params[:moods])

      # NOTE: Make sure we got some songs back
      if songs.present?
        @songs = songs.uniq.sorted_by_title.page params[:page]
        flash[:success] = ' Filtering song moods on ' + moods + '.'
      else
        flash[:alert] = ' There are no songs matching moods: ' + moods + '.'
      end
    end

    # NOTE:  Filter on themes
    if params[:themes].present?
      # NOTE: Get all songs with the requested theme(s)
      songs = Song.joins(:themes).where("theme_id IN (?)", params[:themes])

      # NOTE: Get the titles of the selected themes and put them in a sentence
      themes = Theme.make_sentence(params[:themes])

      # NOTE: Make sure we got some songs back
      if songs.present?
        @songs = songs.uniq.sorted_by_title.page params[:page]
        flash[:success] = ' Filtering song themes on ' + themes + '.'
      else
        flash[:alert] = ' There are no songs matching themes: ' + themes + '.'
      end
    end

    if !@songs.present?
      @songs = Song.sorted_by_title.page params[:page]
    end

    render "index"

    # Discard the flash notice
    flash.discard
  end

  # GET /songs
  # GET /songs.json
  def index
    @title ='Music Search'
    @leading_text = 'Please feel free to browse for ideas. No sign-in is needed. You can search the entire catalog for: melodic moods, lyrical themes, title, genre, etc.'
    @subtitle = ''

    # NOTE: Set the value of songs to "All" by default
    # @songs = Song.all

    if params[:q].present?
      @songs_searched = []
      @search_string = params[:q].split

      @search_string.each  do |s|

        # # NOTE: Get possible artists.
        # artist_id = Artist.search_by_name(params[:q])
        # if artist_id.present?
        #   artist_songs = Artist.search_by_id(artist_id)
        # else
          artist_songs = []
        # end

        # # NOTE: Get possible albums.
        # album_id = Album.search_by_name(params[:q])
        # # album_songs = Song.search_album(album_id)

        # if album_id.present?
        #   album_songs = Album.search_by_id(album_id)
        # else
          album_songs = []
        # end

        # NOTE: Get possible genres.
        # genre_id = Genre.search_by_name(params[:q])
        genre_id = Genre.search_by_name(s)
        genre_songs = Song.search_genre(genre_id)

        # NOTE: Get possible moods.
        mood_id = Mood.search_by_name(s)
        mood_songs = Song.search_mood(mood_id)

        # NOTE: Get possible themes.
        theme_id = Theme.search_by_name(s)
        theme_songs = Song.search_theme(theme_id)

        #NOTE: Get possible songs
        songs_list = Song.search(s)

        @songs_searched = (@songs_searched + songs_list + mood_songs + theme_songs + genre_songs + album_songs + artist_songs).uniq

      end

      # Check to see if the array is empty
      if @songs_searched.blank?
        flash[:alert] = (' There are no songs containing the term(s): <em><strong>' + params[:q].to_s + '</strong></em>.').html_safe
      else
        @songs = Kaminari.paginate_array(@songs_searched).page(params[:page])
      end

      # Discard the flash notice
      flash.discard
    end

    # NOTE: If nothing came back from the search, show ALL songs
    if !@songs.present?
      @moods = Mood.sorted
      @themes = Theme.all
      @songs = Song.all.order(:title).page params[:page]
    end

  end

  # GET /songs/1
  # GET /songs/1.json
  def show

    @album = Album.find(@song.album.id)
    @artist = Artist.find(@album.artist.id)
    @genres = Genre.joins(:songs).where(songs: {id: @song.id})
    @moods = Mood.joins(:songs).where(songs: {id: @song.id})
    @themes = Theme.joins(:songs).where(songs: {id: @song.id})
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        flash[:success] = ' Song was successfully created.'
        format.html { redirect_to @song }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)

        # NOTE: Clear the genres so we can update them if needed
        @song.genres.clear

        # NOTE: Update the genre relations.
        if params[:genres].present?
          params[:genres].each do |genre|
            @song.genres << @genres.find(genre)
          end
        end

        # NOTE: Clear the moods so we can update them if needed
        @song.moods.clear

        # NOTE: Update the mood relations.
        if params[:moods].present?
          params[:moods].each do |mood|
            @song.moods << @moods.find(mood)
          end
        end

        # NOTE: Clear the themes so we can update them if needed
        @song.themes.clear

        # NOTE: Update the theme relations.
        if params[:themes].present?
          params[:themes].each do |theme|
            @song.themes << @themes.find(theme)
          end
        end

        # flash[:notice] = song_params
        # flash[:alert] = params
        flash[:success] = 'Song was successfully updated.'
        format.html { redirect_to @song }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    def get_albums
      @albums = Album.all
    end

    def set_artist
      @artists = Artist.all
    end

    def get_genres
      @genres = Genre.all
    end

    def get_moods
      @moods = Mood.all
    end

    def get_themes
      @themes = Theme.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :description, :original_release_date, :length, :album_id, :mood, :theme, :genre, :cover_art, :audio, :writers, :isrc)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<!-- <pre>< % = @song.to_yaml %></pre> -->
<!-- <pre>< % =  @moods.to_yaml %></pre> -->


<%= form_for(@song, multipart: true) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3><%= f.label :title %></h3>
    <%= f.text_field :title, placeholder: 'Song Title' %>
  </div>

  <div class="field">
    <h3><%= f.label :description %></h3>
    <%= f.bootsy_area :description, placeholder: 'Enter a description, history, lyrics, etc.' %>
  </div>

  <div class="field">
    <h3><%= f.label :original_release_date %></h3>
    <%= f.date_select :original_release_date, {start_year:1960, end_year: Date.today.year, order: [:month, :day, :year]}, { :class => 'xform-control' } %>
  </div>

  <div class="field">
    <h3><%= f.label :writers %></h3>
    <%= f.text_field :writers, placeholder: 'Provide the writers for this song.' %>
  </div>

  <div class="field">
    <h3><label for="song_ISRC">ISRC#</label></h3>
    <%= f.text_field :isrc, maxlength: 15, placeholder: 'CC-XXX-YY-NNNNN' %>
  </div>

  <div class="field">
    <h3><%= f.label :length %></h3>
    <%= f.text_field :length, maxlength: 8, placeholder: 'hh:mm:ss' %>
  </div>

  <div class="field">
    <h3><%= f.label :album %></h3>
    <%= f.select(:album_id, @albums.map {|a| [a.title, a.id]}) %>
  </div>

  <% #NOTE: Audio File %>
  <div class="field">
    <h3><%= f.label :audio %></h3>
    <div class="row">

      <% if @song.audio.blank? %>
        <div class="col-sm-12">
        <%= f.file_field :audio %>
        </div>
      <% else %>
        <div class="col-sm-6">
          <%= f.file_field :audio, value: @song.audio_file_name %>
          <p class="current-file muted"><em>The current file name is: <strong><%= @song.audio_file_name %></strong>.</em></p>
        </div>
        <div class="col-sm-6">
          <audio controls="controls">
            Your browser does not support the <code>audio</code> element.
            <source src="<%= @song.audio.url(:original) %>" type="<%= @song.audio.content_type %>" volume="0.5" >
          </audio>
        </div>
      <% end %>


    </div>
    <%= f.hidden_field :hidden_audio_file, value: @song.audio_file_name %>
  </div>

  <% #NOTE: Cover Art %>
  <div class="field">
    <h3><%= f.label :cover_art %></h3>
    <div class="row">

    <% if @song.cover_art.blank? %>
      <div class="col-sm-12">
        <%= f.file_field :cover_art %>
      </div>
    <% else %>
      <div class="col-sm-6">
        <%= f.file_field :cover_art, value: @song.cover_art_file_name %>
        <p class="current-file muted"><em>The current file name is: <strong><%= @song.cover_art_file_name %></strong>.</em></p>

      </div>
      <div class="col-sm-6">
        <%= image_tag @song.cover_art.url(:medium), class: "img-responsive center-block thumbnail" %>
      </div>
    <% end %>

    </div>
    <%= f.hidden_field 'hidden_cover_art', value: @song.cover_art_file_name, id: "hidden_cover_art" %>
  </div>

  <div class="field">
    <h3><label>Genres</label></h3>
    <section class="genres">

      <% # NOTE: Loop over each genre so we can filter on them.
      @genres.sorted.each do |genre|

        # NOTE: Check to see if we are filtering for genres so we can mark them as selected
        if @song.genre_ids.present?
          selected = @song.genre_ids.reject { |a| a != genre.id }
        else
          selected = nil
        end
        %>

      <div class="checkbox">
        <% if selected.blank? %>
          <%= check_box_tag 'genres[]', genre.id, false %>
        <% else %>
          <%= check_box_tag 'genres[]', genre.id, true %>
        <% end %>

        <label for="<%= genre.id %>"><%= genre.title.titleize %></label>
      </div>
      <% end %>

    </section>
  </div>

  <div class="field">
    <h3><label>Moods</label></h3>
    <section class="moods">

      <% # NOTE: Loop over each mood so we can filter on them.
      @moods.sorted.each do |mood|

        # NOTE: Check to see if we are filtering for moods so we can mark them as selected
        if @song.mood_ids.present?
          selected = @song.mood_ids.reject { |a| a != mood.id }
        else
          selected = nil
        end
        %>

      <div class="checkbox">
        <% if selected.blank? %>
          <%= check_box_tag 'moods[]', mood.id, false %>
        <% else %>
          <%= check_box_tag 'moods[]', mood.id, true %>
        <% end %>

        <label for="<%= mood.id %>"><%= mood.title.titleize %></label>
      </div>
      <% end %>

    </section>
  </div>

  <div class="field">
    <h3><label>Themes</label></h3>
    <section class="themes">

      <% # NOTE: Loop over each theme so we can filter on them.
      @themes.sorted.each do |theme|

        # NOTE: Check to see if we are filtering for themes so we can mark them as selected
        if @song.theme_ids.present?
          selected = @song.theme_ids.reject { |a| a != theme.id }
        else
          selected = nil
        end
        %>

      <div class="checkbox">
        <% if selected.blank? %>
          <%= check_box_tag 'themes[]', theme.id, false %>
        <% else %>
          <%= check_box_tag 'themes[]', theme.id, true %>
        <% end %>

        <label for="<%= theme.id %>"><%= theme.title.titleize %></label>
      </div>
      <% end %>

    </section>
  </div>

  <%= f.submit nil, class: "btn btn-primary", role:"button" %>
<% end %>

app/views/songs/_index-admin.html.erb
<!-- Render page title -->
<%=
  @page = Page.find('search')
  render 'application/page_title',
  title: @page.title,
  leading_text: @page.leading_text,
  subtitle: @page.subtitle
%>

<!-- Search Bar -->
<%= render(:partial => "application/search_form") %>

<%= @page.body.html_safe %>

<!-- <section class="song index wow fadeInUp"> -->
<section class="song index">

  <table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Album</th>
      <th>Artist</th>
<!--       <th></th>
      <th>Released</th> -->
      <!-- <th colspan="2">Actions</th> -->
    </tr>
    </thead>
    <tbody>

    <% @songs.each do |song| %>
      <%
        album = Album.find(song.album.id)
        artist = Artist.find(album.artist.id)
        # genres = song.genre_ids
        # aMoods = Mood.find(song.id)
        # aThemes = Theme.find(song.id)

        if song.original_release_date.present?
          release_date = song.original_release_date.to_formatted_s(:year)
        else
          release_date = ''
        end
      %>

      <tr>
        <td><%= link_to song.title, song %><br><small><%= release_date %></small></td>
        <td><%= link_to album.title, album %></td>
        <td><%= link_to artist.name, artist %></td>
<!--         <td> - <%= link_to album.title, album %></td>
        <td align="center"></td> -->
<!--         <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
  </table>

  <%= paginate @songs %>

</section>

<br>

<!-- <%= link_to 'New Song', new_song_path %> -->

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song, class: "btn btn-primary", role:"button" %> |
<%= link_to 'Back', songs_path, class: "btn btn-primary", role:"button" %>

app/views/songs/index.html.erb
<!-- Render page title -->
<%=
  @page = Page.find('search')
  render 'application/page_title',
  title: @page.title,
  leading_text: @page.leading_text,
  subtitle: @page.subtitle
%>

<!-- Search Bar -->
<%= render(:partial => "application/search_form") %>

<%= @page.body.html_safe %>

<!-- <section class="song index wow fadeInUp"> -->
<section class="song index">

  <table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Album</th>
      <th>Artist</th>
<!--       <th></th>
      <th>Released</th> -->
      <!-- <th colspan="2">Actions</th> -->
    </tr>
    </thead>
    <tbody>

    <% @songs.each do |song| %>
      <%
        album = Album.find(song.album.id)
        artist = Artist.find(album.artist.id)
        # genres = song.genre_ids
        # aMoods = Mood.find(song.id)
        # aThemes = Theme.find(song.id)

        if song.original_release_date.present?
          release_date = song.original_release_date.to_formatted_s(:year)
        else
          release_date = ''
        end
      %>

      <tr>
        <td><%= link_to song.title, song %><br><small><%= release_date %></small></td>
        <td><%= link_to album.title, album %></td>
        <td><%= link_to artist.name, artist %></td>
<!--         <td> - <%= link_to album.title, album %></td>
        <td align="center"></td> -->
<!--         <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
  </table>

  <%= paginate @songs %>

</section>

<br>

<!-- <%= link_to 'New Song', new_song_path %> -->

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path, class: "btn btn-primary", role:"button" %>

app/views/songs/search.html.erb
<h1>Songs#song</h1>
<p>Find me in app/views/songs/search.html.erb</p>

app/views/songs/show.html.erb
<!-- <pre>< % = @song.to_yaml %></pre> -->

<%
  if @song.original_release_date.present?
    release_date = @song.original_release_date.to_formatted_s(:year)
  else
    release_date = ''
  end
%>

<article class="song show">

  <header class="page-header">
    <h1>
    <%= @song.title %>
    <small><em><%= release_date %></em></small>
    </h1>

    <% if current_user
      if current_user.admin %>
      <%= link_to 'Edit', edit_song_path(@song), class: 'btn btn-primary' %>
    <% end
    end %>
  </header>

  <div class="row">
    <div class="col-md-4">
      <!-- <img src="http://placehold.it/250x250"> -->

      <%=
      if @song.cover_art_file_name.present?
        image_tag @song.cover_art.url(:medium), class: "img-responsive center-block thumbnail"
      else
        image_tag "//placehold.it/250x250/ebf8ff/666666?text=No+Preview", class: "img-responsive center-block thumbnail"
      end
      %>
    </div>

    <div class="col-md-8">

      <h3>Information</h3>
      <p><strong>Artist:</strong> <%= link_to @artist.name, @artist  %></p>
      <p><strong>Writer(s):</strong> <%= @song.writers  %></p>
      <p><strong>Album:</strong> <%= link_to @album.title, @album  %></p>
      <p><strong>ISRC #:</strong> <%= @song.isrc %></p>
      <p><strong>Duration:</strong> <%= @song.length %></p>

      <p><strong>Genres:</strong>

      <%
      #NOTE: Check to see if there are genres
      if @genres.present?
      genre_last = @genres.last
      %>
        <% @genres.each do |genre| %>
          <%= genre.title %>

          <%
          # NOTE: Add a comma if it's not the last genre.
          if genre != genre_last
          %>

          ,&nbsp;
          <% end %>
        <% end %>
      <% else %>
        -
      <% end %>

      </p>

      <p><strong>Moods:</strong>

      <%
      #NOTE: Check to see if there are moods
      if @moods.present?
      mood_last = @moods.last
      %>
        <% @moods.each do |mood| %>
          <%= mood.title %>

          <%
          # NOTE: Add a comma if it's not the last mood.
          if mood != mood_last
          %>

          ,&nbsp;
          <% end %>
        <% end %>
      <% else %>
        -
      <% end %>

      </p>

      <p><strong>Themes:</strong>

      <%
      #NOTE: Check to see if there are themes
      if @themes.present?
      theme_last = @themes.last
      %>
        <% @themes.each do |theme| %>
          <%= theme.title %>

          <%
          # NOTE: Add a comma if it's not the last theme.
          if theme != theme_last
          %>

          ,&nbsp;
          <% end %>
        <% end %>
      <% else %>
        -
      <% end %>

      </p>

      <% if @song.audio_file_name %>
      <audio controls="controls">
        Your browser does not support the <code>audio</code> element.
        <source src="<%= @song.audio.url(:original) %>" type="<%= @song.audio.content_type %>" volume="0.5" >
      </audio>
      <% end %>
    </div>
  </div>


  <% if @song.description  %>
  <div class="description">
    <h3>Description</h3>
    <p><%= @song.description.html_safe %></p>
  </div>
  <% end %>

</article>