config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users, path: "authorize", path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'cmon_let_me_in'
  }

  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  root 'application#index'

  get 'about' => 'application#about'
  get 'solicit' => 'application#solicit'

  resources :artists

  get 'songs/filter' => 'songs#filter'
  resources :songs

  resources :albums

  resources :genres

  resources :moods

  resources :themes

  resources :messages
    get 'messages/new/project' => 'messages#new_project'

  resources :contacts

  resources :pages

  match ':controller(/:action(/:id(.:format)))', :via => [:get, :post]
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :artist
  has_many :songs

  # Add file attachments
  has_attached_file :cover_art, :styles => { :large => "300x300", :medium => "250x250>", :thumb => "125x125>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover_art, :content_type => /\Aimage\/.*\Z/

  scope :sorted, lambda { order("albums.name ASC") }
  scope :sorted_rev, lambda { order("albums.name DESC") }

  def self.search_by_artist(q)
    where("artist_id is ?", "#{q}")
  end

  # NOTE: Search for a album by name
  def self.search_by_name(name)
    aAlbum = where('title ILIKE ?', name).first

    # NOTE: Check to see if there's a album by that name
    if aAlbum.present?
      aAlbum.id
    else
      ''
    end
  end

  # NOTE: Search for a album by id
  def self.search_by_id(id)
    find(id)
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums

  # Add file attachments
  has_attached_file :cover_art, :styles => { :large => "300x300", :medium => "250x250>", :thumb => "125x125>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover_art, :content_type => /\Aimage\/.*\Z/

  scope :sorted, lambda { order("artists.name ASC") }
  scope :sorted_rev, lambda { order("artists.name DESC") }

  # NOTE: Search for a mood by name
  def self.search_by_name(name)
    aArtist = where('name ILIKE ?', name).first

    # NOTE: Check to see if there's a mood by that name
    if aArtist.present?
      aArtist.id
    else
      ''
    end
  end

  # NOTE: Search for a mood by name
  def self.search_by_id(id)
    find(id)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :songs, :join_table => 'genres_songs'

  scope :sorted, lambda { order("title ASC") }

  def self.search_by_song(id)
    where("song.id ILIKE ?", "#{id}")
  end

  # NOTE: Search for a genre by name
  def self.search_by_name(name)
    aGenre = where('title ILIKE ?', name).first

    # NOTE: Check to see if there's a genre by that name
    if aGenre.present?
      aGenre.id
    else
      ''
    end
  end

  # NOTE: Search for a genre by name
  def self.search_by_id(id)
    find(id)
  end

  def self.make_sentence(ids)
    # NOTE: Get the titles of the selected genres
    genre_titles = []
    ids. each do |m|
      title = '"' + find(m).title.titleize + '"'
      genre_titles << title
    end

    # Put genre titles into a sentence
    genre_titles.to_sentence(two_words_connector: ' or ', last_word_connector: ' or ')
  end

end # end class

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :name, :project, :description
  validates_format_of :email_address, :with => /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/models/mood.rb
class Mood < ActiveRecord::Base
  has_and_belongs_to_many :songs, :join_table => 'moods_songs'

  scope :sorted, lambda { order("title ASC") }

  # NOTE: Search for a mood by name
  def self.search_by_name(name)
    aMood = where('title ILIKE ?', name).first

    # NOTE: Check to see if there's a mood by that name
    if aMood.present?
      aMood.id
    else
      ''
    end
  end

  # NOTE: Search for a mood by name
  def self.search_by_id(id)
    find(id)
  end

  def self.make_sentence(ids)
    # NOTE: Get the titles of the selected moods
    mood_titles = []
    ids. each do |m|
      title = '"' + find(m).title.titleize + '"'
      mood_titles << title
    end

    # Put mood titles into a sentence
    mood_titles.to_sentence(two_words_connector: ' or ', last_word_connector: ' or ')
  end
end

app/models/page.rb
class Page < ActiveRecord::Base

  # NOTE: Find pages by slug
  def self.find(slug)
    find_by_slug(slug)
  end

  def to_param
    slug
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
  has_and_belongs_to_many :genres, :join_table => 'genres_songs'
  has_and_belongs_to_many :moods, :join_table => 'moods_songs'
  has_and_belongs_to_many :themes, :join_table => 'songs_themes'

  # NOTE: Add file attachments
  has_attached_file :cover_art, :styles => { :large => "300x300", :medium => "200x200>", :thumb => "100x100>" }
  validates_attachment_content_type :cover_art,
    :content_type => /\Aimage\/.*\Z/,
    :size => { :less_than => 3.megabytes }

  has_attached_file :audio
  validates_attachment_content_type :audio,
    :content_type => /\Aaudio\/.*\Z/,
    :size => { :less_than => 13.megabytes }

  scope :sorted_by_title, lambda { order("songs.title ASC") }
  # scope :sorted_by_title_reverse, lambda { order("songs.title DESC") }
  # scope :sorted_by_release_date, lambda { order("songs.original_release_date ASC") }
  # scope :sorted_by_release_date_reverse, lambda { order("songs.original_release_date DESC") }

  # scope :search, lambda { |query|
  #   where("title LIKE ?", "%#{query}%")
  # }

  # NOTE: Add pagination
  paginates_per 25

  def self.search(q)

    if q
      # @songs = Song.search(params[:q]).sorted_by_title
      # where("title ILIKE ? OR theme ILIKE ? OR genre ILIKE ? OR mood ILIKE ?", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%")
      where("title ILIKE ?", "%#{q}%")
    # else
      # @songs = Song.all
      # all
    end
  end

  # NOTE: Find songs by mood
  def self.search_mood(uid)
    song_search = Song.joins(:moods).where(moods: {id: uid})
  end

  # NOTE: Find songs by theme
  def self.search_theme(uid)
    song_search = Song.joins(:themes).where(themes: {id: uid})
  end

  # NOTE: Find songs by genre
  def self.search_genre(uid)
    song_search = Song.joins(:genres).where(genres: {id: uid})
  end

  # # NOTE: Find songs by album
  # def self.search_album(uid)
  #   song_search = Song.joins(:albums).where(albums: {id: uid})
  # end

  # # NOTE: Find songs by artist
  # def self.search_artist(uid)
  #   song_search = Song.joins(:albums).where(albums: {id: uid})
  # end
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  has_and_belongs_to_many :songs, :join_table => 'songs_themes'

  scope :sorted, lambda { order("title ASC") }

  # NOTE: Search for a mood by name
  def self.search_by_name(name)
    aTheme = where('title ILIKE ?', name).first

    # NOTE: Check to see if there's a mood by that name
    if aTheme.present?
      aTheme.id
    else
      ''
    end
  end

  # NOTE: Search for a mood by name
  def self.search_by_id(id)
    find(id)
  end

  def self.make_sentence(ids)
    # NOTE: Get the titles of the selected themes
    theme_titles = []
    ids. each do |m|
      title = '"' + find(m).title.titleize + '"'
      theme_titles << title
    end

    # Put theme titles into a sentence
    theme_titles.to_sentence(two_words_connector: ' or ', last_word_connector: ' or ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :recoverable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<%
  # NOTE: Set classes for non-Song controller pages
  if controller_name == "songs" and (action_name == "index" or action_name =="filter")
    main_col_1 = "col-md-9"
    main_col_2 = "col-md-3"
  else
    main_col_1 = "col-md-12"
    main_col_2 = "hidden invisible"
  end

  # NOTE: Clear out the filters
  if params[:action] == 'filter'
    @clear_filter = link_to 'Clear', {:controller => :songs, :action => :index}, :class => 'btn btn-default btn-xs'
  else
    @clear_filter = ''
  end

%>


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) + " :: Somerset Songs Publishing" : "Somerset Songs Publishing" %></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag("application", :media => 'all') %>
    <%= javascript_include_tag "modernizr" %>
    <%= csrf_meta_tags %>

    <!-- Loading third party fonts -->
    <link href="//fonts.googleapis.com/css?family=Roboto+Slab:300,400,700" rel="stylesheet" type="text/css">
  </head>

  <body>

    <div id="site-content">

      <header class="site-header" data-spy="affix">

      <% if current_user %>
          <%= render 'application/header_top' %>
      <% end %>

        <div class="bottom-header">
          <div class="container">
            <!-- #branding -->
            <!--
            < % = # link_to image_tag('header-logo-203Wx90H.png', :alt => 'Somerset Songs Logo.', :class => 'logo-icon') + '<h1 class="site-title">Somerset Songs <span>Publishing</span></h1><h2 class="site-description">Media Library</h2>'.html_safe, {:action => :index}, :class => "branding pull-left" % >
            -->
            <%= link_to image_tag('SSPLogo-01.png', width: '250', alt: 'Somerset Songs Logo.', class: 'logo-icon'), '/', :class => "branding pull-left" %>

            <nav class="main-navigation pull-right">
              <button type="button" class="menu-toggle">
                <i class="fa fa-bars"></i>
              </button>
              <%= render(:partial => "application/global_navigation") %>
            </nav>
          </div> <!-- .container -->
        </div> <!-- .bottom-header -->
      </header> <!-- .site-header -->

      <main class="content">
        <div class="page-content">

        <!-- Render any notices -->
        <%= render(:partial => "application/flash") %>

        <div class="fullwidth-block">
          <div class="container">
            <div class="row">
              <div class="<%= main_col_1 %>">

                <%= yield %>

              </div>
              <div class="sidebar <%= main_col_2 %>">
                <h2>Filters <%= @clear_filter %></h2>
                  <%= render :partial => "application/filter_moods" if controller_name == "songs" and (action_name == "index" or action_name =="filter") %>
                  <%= render :partial => "application/filter_themes" if controller_name == "songs" and (action_name == "index" or action_name =="filter") %>
                  <%= render :partial => "application/filter_genres" if controller_name == "songs" and (action_name == "index" or action_name =="filter") %>
              </div>
            </div>
          </div>
        </div>
      </main> <!-- .content -->

      <%= render 'application/footer' %>

    </div> <!-- #site-content -->

   <!--  // <script src="js/jquery-1.11.1.min.js"></script>
    // <script src="js/plugins.js"></script>
    // <script src="js/app.js"></script> -->

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>

  </body>

</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :leading_text %><br>
    <%= f.text_field :leading_text %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.bootsy_area :body %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page, {class: 'btn btn-primary btn-md'} %> |
<%= link_to 'Back', pages_path, {class: 'btn btn-primary btn-md'} %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pages</h1>

<button type="button" class="btn btn-secondary btn-md"><%= link_to ' New Page', new_page_path, class: 'fa fa-plus-square' %></button>

<section class="song index">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th width="60%">Title</th>
        <th width="25%">Slug</th>
        <th colspan="3" width="15%"></th>
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.title %></td>
          <td><%= page.slug %></td>
          <td><%= link_to 'Show', page %></td>
          <td><%= link_to 'Edit', edit_page_path(page) %></td>
          <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @page.subtitle %>
</p>

<p>
  <strong>Leading Text:</strong>
  <%= @page.leading_text %>
</p>

<p>
  <strong>Body:</strong>
  <%= @page.body.html_safe %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'All Pages', pages_path %>