config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users, path: "authorize", path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'cmon_let_me_in'
  }

  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

  root 'application#index'

  get 'about' => 'application#about'
  get 'solicit' => 'application#solicit'

  resources :artists

  get 'songs/filter' => 'songs#filter'
  resources :songs

  resources :albums

  resources :genres

  resources :moods

  resources :themes

  resources :messages
    get 'messages/new/project' => 'messages#new_project'

  resources :contacts

  resources :pages

  match ':controller(/:action(/:id(.:format)))', :via => [:get, :post]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'application'

  def get_page_metadata
    @page = Page.find_by_name(params[:name])
    @pagetitle = @page.title
  end

  def index
    render 'index'
  end

  def about
    render 'about'
  end

  def solicit
    render 'solicit'
  end

  def services
    render 'services'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_dates.html.erb
<div class="row">
  <div class="medium-12 columns text-right">
    <h6>
      <small>
        <% if ( @updated ) %>
          <strong>Updated:</strong> <%= time_tag @updated %> -
        <% end %>

        <%
        # Check to see if there's a creation date to show.
        if ( @created )
        %>
        <strong>Created:</strong> <%= time_tag @created %>
        <%
        end
        %>
      </small>
    </h6>
  </div>
</div>

app/views/application/_filter_genres.html.erb
<aside class="genres boxed-content">
  <h3 class="wow">Genres</h3>
  <p class="wow">Select one or more of the <%= Genre.count %> genres to filter on.</p>

  <%= form_tag({controller: "songs", action: "filter"}, :method => "get", id: "filter-genres") do %>
    <div class="row">
      <div class="col-xs-12">
        <div class="input-group">

          <% # NOTE: Loop over each genre so we can filter on them.
          Genre.sorted.each do |genre|

            # NOTE: Check to see if we are filtering for genres so we can mark them as selected
            if params[:genres].present?
              t = params[:genres].reject { |a| a != genre.id.to_s }
            else
              t = nil
            end
            %>

          <div class="checkbox">
            <label for="<%= genre.id %>">
            <% if t.blank? %>
              <%= check_box_tag 'genres[]', genre.id, false %>
            <% else %>
              <%= check_box_tag 'genres[]', genre.id, true %>
            <% end %>
            <%= genre.title.titleize %></label>
          </div>
          <% end %>

        </div>
      </div>
    </div>
    <%= submit_tag("Filter", {class: "center-block btn btn-default"}) %>
  <% end %>
</aside>

app/views/application/_filter_moods.html.erb
<aside class="moods boxed-content">
  <h3 class="wow">Moods</h3>
  <p class="wow">Select one or more of the <%= Mood.count %> moods to filter on.</p>
  <%= form_tag({controller: "songs", action: "filter"}, :method => "get", id: "filter-moods") do %>
    <div class="row">
      <div class="col-xs-12">
        <div class="input-group">

          <% # NOTE: Loop over each mood so we can filter on them.
          Mood.sorted.each do |mood|

            # NOTE: Check to see if we are filtering for moods so we can mark them as selected
            if params[:moods].present?
              t = params[:moods].reject { |a| a != mood.id.to_s }
            else
              t = nil
            end
            %>

          <div class="checkbox">
            <label for="<%= mood.id %>">
            <% if t.blank? %>
              <%= check_box_tag 'moods[]', mood.id, false %>
            <% else %>
              <%= check_box_tag 'moods[]', mood.id, true %>
            <% end %>
            <%= mood.title %></label>
          </div>
          <% end %>

        </div>
      </div>
    </div>
    <%= submit_tag("Filter", {class: "center-block btn btn-default"}) %>
  <% end %>
</aside>

app/views/application/_filter_themes.html.erb
<aside class="themes boxed-content">
  <h3 class="wow">Themes</h3>
  <p class="wow">Select one or more of the <%= Theme.count %> themes to filter on.</p>
  <%= form_tag({controller: "songs", action: "filter"}, :method => "get", id: "filter-themes") do %>
    <div class="row">
      <div class="col-xs-12">
        <div class="input-group">

          <% # NOTE: Loop over each theme so we can filter on them.
          Theme.sorted.each do |theme|

            # NOTE: Check to see if we are filtering for themes so we can mark them as selected
            if params[:themes].present?
              t = params[:themes].reject { |a| a != theme.id.to_s }
            else
              t = nil
            end
            %>

          <div class="checkbox">
            <label for="<%= theme.id %>">
            <% if t.blank? %>
              <%= check_box_tag 'themes[]', theme.id, false %>
            <% else %>
              <%= check_box_tag 'themes[]', theme.id, true %>
            <% end %>
            <%= theme.title.titleize %></label>
          </div>
          <% end %>

        </div>
      </div>
    </div>
    <%= submit_tag("Filter", {class: "center-block btn btn-default"}) %>
  <% end %>
</aside>

app/views/application/_flash.html.erb
<%
# Possible flash messages...
# flash [:success] = 'This is a success'
# flash [:notice] = 'This is a notice'
# flash [:warning] = 'This is a warning'
# flash [:alert] = 'This is a alert'
 %>

<% if flash[:alert].present? %>
  <div class="fullwidth-block">
    <div div-alert class="container alert alert-danger" role="alert">
      <h4><i class="fa fa-exclamation"></i><%= flash[:alert] %></h4>
    </div>
  </div>
<% end %>

<% if flash[:notice].present? %>
  <div class="fullwidth-block">
    <div div-alert class="container alert alert-info" role="alert">
      <h4><i class="fa fa-bolt"></i><%= flash[:notice] %></h4>
    </div>
  </div>
<% end %>

<% if flash[:success].present? %>
  <div class="fullwidth-block">
    <div div-alert class="container alert alert-success" role="alert">
      <h4><i class="fa fa-thumbs-o-up"></i><%= flash[:success] %></h4>
    </div>
  </div>
<% end %>

<% if flash[:warning].present? %>
  <div class="fullwidth-block">
    <div div-alert class="container alert alert-warning" role="alert">
      <h4><i class="fa fa-exclamation"></i><%= flash[:warning] %></h4>
    </div>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="site-footer">
  <div class="container">

    <div class="row">
      <div class="col-md-6">
        <p><a href="tel:(212) 717-4473">Call Us: (212) 717-4473</a></p>
        <p class="copy">Copyright 2015 Somerset Songs Publishing. All rights reserved</p>
      </div>

      <div class="col-md-6 align-right">
        <div class="social-links">
          <a href="https://www.facebook.com/SomersetSongs" class="facebook"><i class="fa fa-facebook"></i></a>
<!--           <a href="#" class="twitter"><i class="fa fa-twitter"></i></a> -->
          <a href="tel:(212) 717-4473" class="phone"><i class="fa fa-phone"></i></a>
          <a href="mailto:licensing@somersetsongs.com" class="email"><i class="fa fa-envelope"></i></a>
          <% if current_user %>
            <%= link_to '', rails_admin.dashboard_path, class: 'fa fa-server' %>
            <%= link_to '', destroy_user_session_path, method: :delete, class: 'fa fa-sign-out' %>
          <% else %>
            <a href="<%= new_user_session_path %>"><i class="fa fa-sign-in"></i></a>
          <% end %>

        </div> <!-- .social-links -->

      </div>
    </div>

  </div>
</footer> <!-- .site-footer -->

app/views/application/_global_navigation.html.erb
<ul class="menu">
    <li class="menu-item"><%= link_to "Home", "/" %></li>
    <li class="menu-item"><%= link_to "Music Search", songs_path %></li>
    <li class="menu-item"><%= link_to "Music Request", "/solicit" %></li>
    <!-- <li class="menu-item"><%= link_to "Albums", albums_path %></li> -->
    <!-- <li class="menu-item"><%= link_to "Artists", artists_path %></li> -->

    <!-- <li class="menu-item"><a href="news.html">News</a></li> -->
    <!-- <li class="menu-item"><a href="services.html">Services</a></li> -->
    <li class="menu-item"><%= link_to "Contact", contacts_path %></li>
  </ul>

app/views/application/_header_top.html.erb
<div class="top-header">
  <div class="container">
    <!-- <a href="tel:80049123441">Call Us: (800) 1234567</a> -->
    <h2 class="pull-left" style="margin:0;">Hello <%= current_user.name ? current_user.name.titleize : 'Some User' %>!</h2>

    <!-- .member-navigation -->
    <nav class="member-navigation pull-right">
      <!-- <a href="#"><i class="fa fa-user"></i> Register</a> -->
      <!-- <a href="#"><i class="fa fa-lock"></i> Login</a> -->
      <%  if current_user.admin %>
        <%= link_to " Back Office", rails_admin.dashboard_path, class: 'fa fa-server' %>

        <% if @page.present?
          if @page.id.present?
        %>

          <%= link_to ' Edit Content', edit_page_path(@page), class: 'fa fa-edit' %>
        <% end
        end %>

        <% if @song %>
          <%= link_to ' Edit Song', edit_song_path(@song), class: 'fa fa-edit' %>
        <%end %>

        <% end %>
      <%= link_to " Logout", destroy_user_session_path, method: :delete, class: 'fa fa-sign-out' %>
    </nav>
  </div> <!-- .container -->
</div> <!-- .top-header -->

app/views/application/_page_title.html.erb
<header>
  <h1 class="page-title"><%= title %>
    <% if subtitle != '' %>
      <small class="subheader"><%= subtitle %></small>
    <% end %>
  </h1>

  <% if leading_text %>
    <p class="leading muted"><%= leading_text %></p>
  <% end %>
</header>

app/views/application/about.html.erb
<div class="fullwidth-block">
  <h1>Welcome to the World of Foreigner Music</h1>

  <p class="leading muted">Please feel free to browse for ideas. No sign in is needed. You can search the entire catalog for:</p>

  <ul>
    <li>Melodic Moods</li>
    <li>Lyrical Themes</li>
    <li>Song Title</li>
    <li>Artist Name</li>
  </ul>

  <p>Or you can complete the Music Search request with a brief description of what you are looking for and we will respond with music suggestions.</p>

  <!-- Search Bar -->
  <div class="search-bar">
    <%= render(:partial => "application/search_form") %>
  </div>

  <h3>All music is pre-cleared and available for immediate approval.</h3>

</div>

app/views/application/contact.html.erb
<%
  @page = Page.find('contact')
%>
<div class="fullwidth-block">
  <h1><%= @page.title %>

    <% if @page.subtitle %>
      <small class="subheader"><%= @page.subtitle %></small>
    <% end %>
  </h1>

  <% if @page.leading_text %>
    <p class="leading muted"><%= @page.leading_text %></p>
  <% end %>

  <% if @page.body %>
    <%= @page.body.html_safe %>
  <% end %>

  <section class="contact">
    <table class="table table-hover table-striped table-condensed">
    <thead>
      <tr>
        <th>Location</th>
        <th>Contact</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><strong>USA, Canada, France, Germany,  UK &amp; Eire</strong></td>
        <td>
          <p>Michele Bourgerie<br>
          Licensing@Somerset Songs.com<br>
          Somerset Songs Publishing, Inc.<br>
          214 East 70th Street<br>
          New York, New York 10021<br>
          (212) 717-4473</p>
        </td>
      </tr>
      <tr>
        <td><strong>Argentina, Chile, Bolivia, Paraguay, Uruguay</strong></td>
        <td>
          <p>John Nathan<br>
          jnathan@omsasongs.com<br>
          Organizacion Musical Sudamericana (OMSA) SRL<br>
          Larrea 1106 (5A)<br>
          1117 Buenos Aires<br>
          (54-11) 4824-5577</p>
        </td>
      </tr>
      <tr>
        <td><strong>Brazil</strong></td>
        <td>
          <p>Simone de Aquino<br>
          simone@fermatadobrasil.com.br<br>
          Fermata Do Brasil Ltda.<br>
          Rua da Consolacao, 2697 <br>
          Sao Paulo SP Brasil<br>
          (55-11) 3060 8614<br>
          www.fermatadobrasil.com.br </p>
        </td>
      </tr>
      <tr>
        <td><strong>Australia, New Zealand </strong></td>
        <td>
          <p>Angela Blackhall<br>
            Angela.Blackhall@umusic.com<br>
            Universal Music Publishing Group - Australia<br>
            150 William Street<br>
            Woolloomooloo, NSW 2011<br>
            +61 (0) 2 9207 0500</p>
          </td>
      </tr>
      <tr>
        <td><strong>Benelux</strong></td>
        <td>
          <p>Jitze de Raaff<br>
          Jitze.deRaaff@ctm.nl<br>
          CTM Publishing BV<br>
          Emmastraat 21 - 1211 NE Hilversum<br>
          The Netherlands<br>
          +31 35 647 4040 <br>
          www.ctm.nl</p>
        </td>
      </tr>
      <tr>
        <td><strong>Italy</strong></td>
        <td>
          <p>Leonardo Germinario<br>
          Warner Chappell Music Italiana S.r.l.<br>
          P.za Della Repubblica, 14/16<br>
          20124 Milano<br>
          Italy<br>
          0039-02-637831</p>
        </td>
      </tr>
      <tr>
        <td><strong>Japan</strong></td>
        <td>
          <p>Manabu Kuretani<br>
          kuretani@fujipacific.co.jp<br>
          FujiPacific Music Inc.<br>
          Tokyo Tatemono Aoyama Bldg., 6F 3-3-5<br>
          Kita-Aoyama Minato-ku, Tokyo 107-0061<br>
          Japan<br>
          813-3796-8603</p>
        </td>
      </tr>
      <tr>
        <td><strong>Scandinavia</strong></td>
        <td>
          <p>Marcus Cedervall<br>
          marcus.cedervall@warnerchappell.com<br>
          Warner/Chappell Music Scandinavia AB<br>
          Pipersgatan 27<br>
          S-104 22 Stockholm, Sweden<br>
          +46 8 622 09 00<br>
          www.warnerchappell.se</p>
        </td>
      </tr>
      <tr>
        <td><strong>South Africa</strong></td>
        <td>
          <p>Geoff Paynter<br>
          geoff@geoffpaymusic.co.za<br>
          Geoff Paynter Music Publishing C.C.<br>
          P.O. Box 2031, Fourways 2055<br>
          Sandton 2191 South Africa<br>
          +27 11 706 0053</p>
        </td>
      </tr>
      <tr>
        <td><strong>SouthEast Asia</strong></td>
        <td>
          <p>Ivan Hui<br>
          ivan@fujipacific-sea.com<br>
          FujiPacific Music (S.E. Asia) Ltd.<br>
          10/F Po Wah Commercial Center<br>
          226 Hennessy Road<br>
          Wanchai, Hong Kong<br>
          (852) 27892236</p>
        </td>
      </tr>
      </tbody>
    </table>
  </section>

  <!-- <h3>All music is pre-cleared and available for immediate approval.</h3> -->

</div>

app/views/application/index.html.erb
<%
  # @page = Page.find('welcome')
%>
        <div class="fullwidth-block feature-section">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="feature">
                  <h1><%= Page.find('welcome').title %>

                  <% if Page.find('welcome').subtitle %>
                    <small class="subheader"><%= Page.find('welcome').leading_text %></small>
                  <% end %>
                  <%  if current_user
                      if current_user.admin %>
                    <%= link_to '<button type="button" class="btn btn-info btn-sm btn-edit"><i class="fa fa-edit">&nbsp;Edit Content</i></button>'.html_safe, edit_page_path( Page.find('welcome')) %>
                  <% end
                  end %>
                  </h1>

                  <% if Page.find('welcome').leading_text %>
                    <p class="leading muted"><%= Page.find('welcome').leading_text %></p>
                  <% end %>

                  <%= Page.find('welcome').body.html_safe %>
                </div> <!-- .feature -->
              </div> <!-- .col-md-12 -->
            </div> <!-- .row -->
          </div> <!-- .container -->
        </div> <!-- .feature-section -->

        <div class="fullwidth-block about-section">

          <div class="container">

            <div class="row">

              <div class="col-md-6">
                <h2><%= Page.find('welcome-search').title %>
                <%  if current_user
                      if current_user.admin %>
                  <%= link_to '<button type="button" class="btn btn-info btn-sm btn-edit"><i class="fa fa-edit">&nbsp;Edit Content</i></button>'.html_safe, edit_page_path( Page.find('welcome-search'))%>
                <% end
                end %></h2>
                <%= Page.find('welcome-search').body.html_safe %>

                <div style="padding: 13px 0">
                  <%= render(:partial => "application/search_form") %>
                  </div>

              </div>

              <div class="col-md-6">
                <h2><%= Page.find('need-help').title %>
                <%  if current_user
                      if current_user.admin %>
                  <%= link_to '<button type="button" class="btn btn-info btn-sm btn-edit"><i class="fa fa-edit">&nbsp;Edit Content</i></button>'.html_safe, edit_page_path( Page.find('need-help'))%>
                <% end
                end %></h2>
                <%= Page.find('need-help').body.html_safe %>
                <%= link_to 'Music Request', {:controller => :application, :action => :solicit}, :class => 'btn btn-primary btn-lg btn-block' %>
              </div>

            </div> <!-- .row -->

          </div> <!-- .container -->
        </div> <!-- .fullwidth-block -->

app/views/application/music_request.html.erb
<div class="fullwidth-block">
  <h1>Music Request</h1>

  <p class="leading muted">Please feel free to browse for ideas. No sign in is needed. You can search the entire catalog for:</p>

  <ul>
    <li>Melodic Moods</li>
    <li>Lyrical Themes</li>
    <li>Song Title</li>
    <li>Artist Name</li>
  </ul>

  <p>Or you can complete the Music Search request with a brief description of what you are looking for and we will respond with music suggestions.</p>

  <!-- Search Bar -->
  <div class="search-bar">
    <%= render(:partial => "application/search_form") %>
  </div>

  <h3>All music is pre-cleared and available for immediate approval.</h3>

</div>

app/views/application/solicit.html.erb
<%
  @message = Message.new
  @form_class = 'solicit'
  @form_id = 'form-solicit'
  @page = Page.find('solicit')
%>
<div class="fullwidth-block">
  <h1><%= @page.title %>

    <% if @page.subtitle %>
      <small class="subheader"><%= @page.subtitle %></small>
    <% end %>
  </h1>

  <% if @page.leading_text %>
    <p class="leading muted"><%= @page.leading_text %></p>
  <% end %>

  <% if @page.body %>
    <%= @page.body.html_safe %>
  <% end %>

</div>

<div class="fullwidth-block">
  <%= render 'messages/form_project_request' %>
</div>